name: Trigger auto deployment for sidhcds-xck5onkrdtz-ca

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/sidhcds-xck5onkrdtz-ca-AutoDeployTrigger-00960236-5bc8-4d7d-9c65-33deb21de25f.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.SIDHCDSXCK5ONKRDTZCA_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}devcontainer
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: sidhcdsxck5onkrdtzderegistry.azurecr.io
          registryUsername: ${{ secrets.SIDHCDSXCK5ONKRDTZCA_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.SIDHCDSXCK5ONKRDTZCA_REGISTRY_PASSWORD }}
          containerAppName: sidhcds-xck5onkrdtz-ca
          resourceGroup: SidHcds-rg
          imageToBuild: sidhcdsxck5onkrdtzderegistry.azurecr.io/sidhcds-xck5onkrdtz-ca:${{ github.sha }}
          
            

     

