name: Trigger auto deployment for sidhcds-xck5onkrdtz-ca

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/sidhcds-xck5onkrdtz-ca-AutoDeployTrigger-2426d438-5c2e-4029-ad46-47006a7a5748.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.SIDHCDSXCK5ONKRDTZCA_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.SIDHCDSXCK5ONKRDTZCA_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.SIDHCDSXCK5ONKRDTZCA_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}devcontainer
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: github.com/login
          registryUsername: ${{ secrets.SIDHCDSXCK5ONKRDTZCA_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.SIDHCDSXCK5ONKRDTZCA_REGISTRY_PASSWORD }}
          containerAppName: sidhcds-xck5onkrdtz-ca
          resourceGroup: SidHcds-rg
          imageToBuild: github.com/login/sidhcds-xck5onkrdtz-ca:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


