name: Trigger auto deployment for trialbysid-omiomd2l-ca

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/trialbysid-omiomd2l-ca-AutoDeployTrigger-c5810ac7-fc67-47a0-9897-7ac56e65520f.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.TRIALBYSIDOMIOMD2LCA_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.TRIALBYSIDOMIOMD2LCA_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.TRIALBYSIDOMIOMD2LCA_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: trialbysidomiomd2lcxoyqregistry.azurecr.io
          registryUsername: ${{ secrets.TRIALBYSIDOMIOMD2LCA_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.TRIALBYSIDOMIOMD2LCA_REGISTRY_PASSWORD }}
          containerAppName: trialbysid-omiomd2l-ca
          resourceGroup: TrialbySid-rg
          imageToBuild: trialbysidomiomd2lcxoyqregistry.azurecr.io/trialbysid-omiomd2l-ca:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


